Repository directus/api, pull requests merged in 2019-12, with the labels that each got.

#1512 Fix #1508 [Deleting a file attached to an item deletes the item]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug

#1513 Fix #1473 [Remove cookie if token is invalid]
  src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php
Labels: bug

#1524 Fix addUpgradeMigrations
  src/core/Directus/Console/Modules/InstallModule.php
  src/core/Directus/Util/Installation/InstallerUtils.php
Labels: bug

#1530 Check if array keys exist before use and pass filename_disk where needed
  src/core/Directus/Services/FilesServices.php
  src/helpers/file.php
Labels: bug

#1531 Repair / implement folders endpoint
  src/core/Directus/Services/FilesServices.php
  src/core/Directus/Services/FoldersService.php
  src/endpoints/Files.php
  src/endpoints/Folders.php
  src/web.php
Labels: bug, enhancement

#1535 Don't use TableGatewayMiddleware for project deletion
  src/endpoints/Server.php
Labels: bug

#1537 Use correct settings for collection / module listing
  migrations/install/20180220023217_create_roles_table.php
  migrations/upgrades/20191209141700_set_options_collection_listing.php
Labels: bug

#1538 Add project public note field to settings
  migrations/install/20180220023243_create_settings_table.php
  migrations/upgrades/20191209130300_add_project_public_note.php
  src/helpers/settings.php
Labels: enhancement

#1539 Return the relative url of thumbnails including root folder
  src/helpers/all.php
  src/helpers/file.php
Labels: bug

#1570 Translations
  migrations/upgrades/20191213160000_new_translations_structure.php
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: enhancement

#1573 Fix #1556[Return null as foreign object when record is soft deleted]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug

#1583 Fix #1579 [Error uploading file with comma in the name]
  src/endpoints/Assets.php
Labels: bug

#1586 Fix #1518 [Resolve typecasting of variable from integer to string]
  src/helpers/all.php
Labels: bug

#1587 Fix #1475 [Set localhost as activity IP address]
  src/core/Directus/Database/TableGateway/DirectusActivityTableGateway.php
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
  src/core/Directus/Services/ActivityService.php
  src/helpers/all.php
Labels: enhancement
