Repository directus/api, pull requests merged in 2019-08, with the labels that each got.

#1169 Don't use special characters in creation of project auth tokens
  src/core/Directus/Util/Installation/InstallerUtils.php
  src/core/Directus/Util/StringUtils.php
Labels: bug

#1168 Add option to prevent upsizing contained thumbnails
  src/core/Directus/Filesystem/Thumbnailer.php
Labels: enhancement

#1163 added array type to schema
  src/core/Directus/Config/Schema/Base.php
  src/core/Directus/Config/Schema/Group.php
  src/core/Directus/Config/Schema/Schema.php
  src/core/Directus/Config/Schema/Types.php
  src/core/Directus/Config/Schema/Value.php
  src/core/Directus/Filesystem/Files.php
  src/core/Directus/Services/ItemsService.php
  src/helpers/app.php
  tests/api/Config/ContextTest.php
  tests/api/Config/SchemaTest.php
  tests/api/Config/sources/source.json
  tests/api/Config/sources/source.php
Labels: bug

#1183 Issue Fix #1180
  src/core/Directus/Services/AbstractService.php
  src/core/Directus/Services/ItemsService.php
Labels: bug

#1192 Issue fix #1191
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug

#1031 Add 2fa authentication
  composer.json
  migrations/db/seeds/FieldsSeeder.php
  migrations/upgrades/schemas/20190614103321_add_users_2fa_secret_field.php
  migrations/upgrades/schemas/20190618190024_add_enforce_2fa_role_field.php
  src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php
  src/core/Directus/Authentication/Exception/InvalidOTPException.php
  src/core/Directus/Authentication/Exception/Missing2FAPasswordException.php
  src/core/Directus/Authentication/Exception/TFAEnforcedException.php
  src/core/Directus/Authentication/Provider.php
  src/core/Directus/Authentication/User/User.php
  src/core/Directus/Authentication/User/UserInterface.php
  src/core/Directus/Services/AuthService.php
  src/core/Directus/Services/UsersService.php
  src/core/Directus/Services/UtilsService.php
  src/endpoints/Auth.php
  src/endpoints/Users.php
  src/endpoints/Utils.php
Labels: enhancement

#1195 Issue Fix #1194
  src/core/Directus/Services/ItemsService.php
Labels: bug

#1198 Valildation issue of O2M/M2O at data insertion
  src/core/Directus/Services/ItemsService.php
Labels: bug

#1202 Fix #1201 [Resolve internal server on storing global settings]
  src/endpoints/Settings.php
Labels: bug

#1204 Fix #1203 [Remove readonly condition for duration field of directus_files table]
  migrations/upgrades/schemas/20190819070856_update_directus_fields_field.php
  src/core/Directus/Services/FilesServices.php
Labels: bug

#1184 Update collections() method in types.php
  src/core/Directus/GraphQL/Types.php
Labels: enhancement

#1210 Improve YouTube Embed Provider
  src/core/Directus/Embed/Provider/YoutubeProvider.php
Labels: enhancement

#1215 Add check for environment on bootstrap
  src/web.php
Labels: docker

#1218 Fix #1186 [Create new error code for invalid login entity]
  src/core/Directus/Services/AbstractService.php
  src/core/Directus/Services/AuthService.php
  src/core/Directus/Validator/Exception/InvalidRequestException.php
Labels: bug

#1220 Fix #1217 (Changing password over the CLI doesn't work)
  src/core/Directus/Console/Common/User.php
Labels: bug

#1221 Fix #1207 [Permission denied issue when using translation interface]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug

#1233 Fix 1232[Auth token is not refreshed]
  src/core/Directus/Authentication/Provider.php
Labels: bug

#1231 Change Authentication Error code to 114 from 109
  src/core/Directus/Services/AuthService.php
Labels: fixed
