Repository directus/api, pull requests merged in 2020-01, with the labels that each got.

#1585 Rename User-Created Interface to Owner
  migrations/install/20180220023208_create_files_table.php
  migrations/upgrades/20191220102232_update_user_created_to_owner.php
  src/core/Directus/Database/Schema/DataTypes.php
  src/core/Directus/Database/Schema/Object/Collection.php
  src/core/Directus/Database/Schema/Object/Field.php
  src/core/Directus/GraphQL/FieldsConfig.php
Labels: enhancement

#1611 Fix #1572 [Resolve CORS issue]
  src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php
Labels: bug

#1607 Fix #1588 [Fix combined permissions for role and status]
  src/core/Directus/Database/TableGateway/BaseTableGateway.php
Labels: bug

#1601 Fix #1463 [Resolve inconsistency between db schema and directus with NOT NULL/required fields]
  src/core/Directus/Database/Schema/SchemaFactory.php
  src/core/Directus/Database/Schema/Sources/MySQLSchema.php
  src/core/Directus/Services/TablesService.php
Labels: bug

#1596 Fix #1568 [Resolve error when field name corresponds to collection name]
  src/core/Directus/Database/Schema/Object/FieldRelationship.php
  src/core/Directus/Database/Schema/Sources/MySQLSchema.php
  src/core/Directus/Services/ItemsService.php
Labels: bug

#1576 Fix #1555 [Remove file_max_size from settings table]
  migrations/install/20180220023243_create_settings_table.php
  migrations/upgrades/20190709053719_add_file_max_size_setting.php
  migrations/upgrades/20190726064001_update_note_for_default_limit.php
  migrations/upgrades/20191202164205_update_directus_settings.php
  migrations/upgrades/20191202164209_reset_directus_fields.php
  migrations/upgrades/20191216175050_remove_file_max_size.php
  src/core/Directus/Services/FilesServices.php
  src/helpers/file.php
Labels: bug

#1599 Fix #1597 [V8.3.1 API broken when cache enable ]
  src/core/Directus/Services/AbstractService.php
Labels: bug

#1575 Fix #1561 [Password reset token won't invalidate]
  migrations/install/20180220023248_create_users_table.php
  migrations/upgrades/20191216134009_add_user_last_password_update.php
  src/core/Directus/Authentication/Provider.php
  src/core/Directus/Services/AuthService.php
Labels: bug

#1621 Fix #1617 [User CLI Argument Error for Reset Password]
  src/core/Directus/Console/Modules/UserModule.php
Labels: bug

#1622 Fix o2m required error
  src/core/Directus/Services/TablesService.php
Labels: bug

#1410 added ability to authenticate on redis for caching
  src/core/Directus/Application/CoreServicesProvider.php
  src/core/Directus/Config/Schema/Schema.php
Labels: enhancement

#1592 Fix #1502 [Required doesn't work with O2M type]
  src/core/Directus/Database/Schema/SchemaFactory.php
  src/core/Directus/Services/ItemsService.php
Labels: bug

#1641 Fix #1639 [POST /folders is broken]
  src/core/Directus/Services/FoldersService.php
Labels: bug

#1667 Fix #1665 [Error while using Thumbnailer via a Custom Endpoint]
  src/core/Directus/Filesystem/Thumbnailer.php
Labels: bug

#1672 Resolve class not found for project listing
  src/endpoints/Server.php
Labels: bug

#1673 Fix #1659 [Update user-created interface to owner]
  migrations/upgrades/20200121134353_update_user_created_interface.php
Labels: bug

#1671 Fix #1644 [Use TEXT for module_listing / collection_listing]
  migrations/upgrades/20200120170859_update_type_of_collection_listing.php
Labels: bug

#1675 Fix #1660 [SQL error when changing field to not required]
  src/core/Directus/Exception/SQLException.php
  src/core/Directus/Services/TablesService.php
  src/endpoints/Fields.php
Labels: bug

#1631 Fix #1523 [Issue with TableGatewayFactory and ACL in Endpoints]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug

#1630 Fix #1629 [API should return 401 on /users/me without authentication]
  src/core/Directus/Services/UsersService.php
Labels: bug

#1609 Fix #1574 [Return warnings / notices in API when doing something that is impossible]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
  src/core/Directus/Exception/ErrorCodes.php
Labels: enhancement

#1683 Fix #1682 [Make default default_locale in settings null]
  migrations/install/20180220023243_create_settings_table.php
  migrations/upgrades/20191202164205_update_directus_settings.php
Labels: tweak

#1688 Restructure the nav override migration
  migrations/upgrades/20190318173400_add_nav_override.php
Labels: bug

#1690 Fix #1686 [Typecast field of setting table]
  src/endpoints/Settings.php
Labels: bug

#1689 Fix #1681 [Add hook for directus_activity table]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug

#1705 Fix #1700 [PHP warning updating M2O field]
  src/core/Directus/Services/ItemsService.php
Labels: bug

#1706 Fix #1697 [Update login attempts value]
  migrations/install/20180220023243_create_settings_table.php
  migrations/upgrades/20200129100037_update_login_attempt_value.php
Labels: tweak

#1707 Fix #1680 [Error in m2m relation]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug

#1709 Fix #1638 [Support of offset and limit for /collections endpoint]
  src/endpoints/Collections.php
Labels: bug

#1708 Fix #1640 [File not removed from disk after deletion]
  src/core/Directus/Application/CoreServicesProvider.php
  src/core/Directus/Filesystem/Files.php
  src/core/Directus/Services/FilesServices.php
Labels: bug

#1713 Fix #1712 [Messages should only be returned if there are any]
  src/core/Directus/Database/TableGateway/RelationalTableGateway.php
Labels: bug
